apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    service: service-b
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: grpc
    port: 5001
    targetPort: 5001
  selector:
    service: service-b
