apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-b
spec:
  hosts:
  - "*"
  gateways:
  - service-b-gateway
  http:
  - match:
    - uri:
        prefix: /service-b
    route:
    - destination:
        host: service-b
        port:
          number: 80